#pragma once

class c_base_entity;
class c_base_weapon;
class c_user_cmd;
class c_player_data;
class c_entity_data;
class c_aimbot_settings;
class c_player_esp_settings;
class c_world_esp_settings;
class c_player_chams_settings;
class c_world_chams_settings;
class c_player_resource;
class c_steamid;
class ctf_party;
class c_party_chat_fragment;
class s_lc_record;
struct s_active_headshot_threat;

namespace utils{
  c_player_data*           get_player_data(i32 index);
  c_entity_data*           get_entity_data(i32 index);
  bool                     reset_transform(i32 index);
  bool                     reset_lag_comp_data(i32 index);
  bool                     reset_player_data(i32 index);
  void                     reset_all_lag_comp_data();
  void                     reset_all_player_data();
  c_aimbot_settings*       get_aimbot_settings();
  c_player_esp_settings*   get_player_esp_settings(i32 type);
  c_player_esp_settings*   get_player_esp_settings(c_base_player* player);
  c_world_esp_settings*    get_world_esp_settings(i32 type);
  c_world_esp_settings*    get_world_esp_settings(c_base_entity* entity);
  c_player_chams_settings* get_player_chams_settings(i32 type);
  c_player_chams_settings* get_player_chams_settings(c_base_player* player);
  c_world_chams_settings*  get_world_chams_settings(i32 type);
  c_world_chams_settings*  get_world_chams_settings(c_base_entity* entity);
  c_player_resource*       get_player_resource();
  std::wstring             get_player_class_name(u8 class_id);
  vec3                     trace_line(vec3 start, vec3 end, u32 mask = 0, u32 custom_trace_filter = 0);
  float                    attrib_hook_float(float a1, std::string str, void* a3, void* a4, bool a5);
  i32                      attrib_hook_int(i32 a1, std::string str, void* a3, void* a4, bool a5);
  float                    get_weapon_hit_chance(c_base_entity* target, vec3 aim_angle);
  void                     create_tf2_marker(i32 owner_index, vec3 pos, std::string text, float life_time);
  void                     check_to_reset_data(i32 index);
  void                     check_for_party_member(i32 index);
  void                     verify_player_data();
  void                     verify_entity_data();
  bool                     create_entity_data(c_base_entity* entity);
  float                    get_command_latency();
  float                    get_latency();
  void                     update_lookat_trace();
  bool                     is_truce_active();
  bool                     is_playing_mvm();
  bool                     is_playing_mannpower();
  bool                     is_in_setup();
  bool                     is_player_ready(i32 index);
  void                     set_playing_mvm(bool state);
  ctf_party*               get_party();
  bool                     medic_mode(c_base_entity* player, bool& out);
  bool                     engineer_mode(c_base_entity* entity, bool& out);
  bool                     wait_lag_fix(c_base_player* player);
  float                    get_damage(c_base_player* player, vec3 attacker_pos = vec3(), vec3 victim_pos = vec3());
  float                    get_heal_bolt_amount(c_base_player* player, vec3 attacker_pos, vec3 victim_pos, c_base_player* victim);
  void                     calculate_sniper_damage(u32 stage);
  void                     draw_hitbox(i32 index, colour clr, float duration = 4.f);
  void                     draw_server_hitbox(i32 index, float duration);
  void                     draw_bounding_box(i32 index, colour clr, float duration = 4.0f);
  bool                     create_custom_matrix(c_base_player* player, vec3 angles, matrix3x4* bone_matrix);
  c_party_chat_fragment*   read_party_chat_packet(i8* str);
  bool                     dispatch_particle_effect(i8* particle_name, vec3 origin, vec3 angle = vec3());
  void                     update_player_information(u32 stage);
  bool                     switch_to_weapon(c_base_weapon* weapon);
  bool                     switch_to_weapon_from_slot(i32 slot);
  bool                     choose_class(u8 i);
  bool                     get_headshot_threats(s_active_headshot_threat* threat_data);
  void                     update_active_threats();
  void                     show_panel(std::string name, bool state);
  bool                     correct_position_for_blast(u8 projectile_type, vec3& pos, c_base_entity* ignore_entity = nullptr);
  bool                     is_in_blast_range(c_base_entity* target, vec3 origin, vec3 pos, float radius);
  bool                     is_in_thirdperson();
  bool                     get_health_colour(i32 health, i32 max_health, colour* hp_col);
  bool                     get_radius_points(vec3 pos, float radius, vec3* list, u32* size, vec3 normal = vec3());
  bool                     is_safe_mode_enabled();
  i32                      calculate_score_board_ping();
};