#pragma once

class c_game_event;
class c_player_resource;
class c_base_entity;
class c_base_player;
class s_user_cmd;
class c_player_data;
class c_entity_data;
class c_player_esp_settings;
class c_player_chams_settings;
class c_world_esp_settings;
class c_world_chams_settings;
class c_world_glow_settings;
class c_steamid;
namespace utils{
  void                     lock_mouse(bool lock);
  void*                    get_interface(std::wstring module, std::string name);
  c_base_player*           localplayer();
  void                     store_cmd_data(s_user_cmd* cmd);
  void                     update_local_data();
  void                     update_player_information(i32 stage);
  c_player_data*           get_player_data(i32 index);
  c_entity_data*           get_entity_data(i32 index);
  c_player_esp_settings*   get_player_esp_settings(i32 type);
  c_player_esp_settings*   get_player_esp_settings(c_base_player* player);
  c_player_chams_settings* get_player_chams_settings(i32 type);
  c_player_chams_settings* get_player_chams_settings(c_base_player* player);
  void                     check_to_reset_data(i32 index);
  void                     check_entity_data(i32 index);
  void                     verify_player_data();
  void                     check_for_steam_friends();
  bool                     reset_lag_comp_data(i32 index);
  void                     reset_all_lag_comp_data();
  bool                     reset_player_data(i32 index);
  bool                     reset_entity_data(i32 index);
  void                     reset_all_player_data();
  void                     reset_all_entity_data();
  c_steamid                get_user_steamid(u32 friends_id);
  void                     send_con_notification(i8* txt);
  bool                     wait_lag_fix(c_base_player* player);
  bool                     is_call_from_rijin(void* addr);
  bool                     is_screen_shot_taken();
  bool                     is_in_thirdperson();
  bool                     is_in_game();
  void                     sync_entity_list_data();
  c_world_esp_settings*    get_world_esp_settings(c_base_entity* entity);
  c_world_chams_settings*  get_world_chams_settings(c_base_entity* entity);
  c_world_glow_settings*   get_world_glow_settings(c_base_entity* entity);
  void                     collect_entity_attachments();
  c_player_resource*       get_player_resource();
  float                    get_command_latency();
  float                    get_latency();
  bool                     process_game_event(c_game_event* event);
  bool                     get_cheater_data_from_network(u32 sid, u32 name_hash, c_net_request_tf_cheater_sid32_response*& _response);
  void                     submit_cheater_to_network(u32 sid, u32 reason);
};