#pragma once

// Go ahead and put game only ones here in, unless it conflicts.
// That way if we happen to lets say make a cheat for tf2 sourcemod. chances are there's gonna be simular stuff used.

// defines
#define PERMANENT_CONDITION -1
#define SPROP_VARINT (1<<5)
#define SPROP_UNSIGNED (1<<0)
#define HEX_RED       0xff0000
#define HEX_YELLOW    0xffff00
#define HEX_GREEN     0x00ff00
#define HEX_BLUE      0x0000ff
#define HEX_LIGHTBLUE 0x00ffff
#define HEX_PURPLE    0xff00ff
#define HEX_ORANGE    0xffb400
#define HEX_GRAY      0xbcbcbc
#define HEX_WHITE     0xffffff

// enums
enum signon_state{
  SIGNONSTATE_NONE        = 0,  // no state yet, about to connect
  SIGNONSTATE_CHALLENGE   = 1,  // client challenging server, all OOB packets
  SIGNONSTATE_CONNECTED   = 2,  // client is connected to server, netchans ready
  SIGNONSTATE_NEW         = 3,  // just got serverinfo and string tables
  SIGNONSTATE_PRESPAWN    = 4,  // received signon buffers
  SIGNONSTATE_SPAWN       = 5,  // ready to receive entity packets
  SIGNONSTATE_FULL        = 6,  // we are fully connected, first non-delta packet received
  SIGNONSTATE_CHANGELEVEL = 7,  // server is changing level, please wait
};

enum {
  OBS_MODE_NONE = 0,  // not in spectator mode
  OBS_MODE_DEATHCAM,  // special mode for death cam animation
  OBS_MODE_FREEZECAM, // zooms to a target, and freeze-frames on them
  OBS_MODE_FIXED,   // view from a fixed camera position
  OBS_MODE_IN_EYE,  // follow a player in first person view
  OBS_MODE_CHASE,   // follow a player in third person view
  OBS_MODE_POI,   // PASSTIME point of interest - game objective, big fight, anything interesting; added in the middle of the enum due to tons of hard-coded "<ROAMING" enum compares
  OBS_MODE_ROAMING, // free roaming

  NUM_OBSERVER_MODES,
};

enum collision_group{
  collision_group_player = 5,
  collision_group_player_movement = 8,
};

enum FCVAR {
  FCVAR_NONE = 0,
  FCVAR_UNREGISTERED = 1 << 0,
  FCVAR_DEVELOPMENTONLY = 1 << 1,
  FCVAR_GAMEDLL = 1 << 2,
  FCVAR_CLIENTDLL = 1 << 3,
  FCVAR_HIDDEN = 1 << 4,
  FCVAR_PROTECTED = 1 << 5,
  FCVAR_SPONLY = 1 << 6,
  FCVAR_ARCHIVE = 1 << 7,
  FCVAR_NOTIFY = 1 << 8,
  FCVAR_USERINFO = 1 << 9,
  FCVAR_CHEAT = 1 << 14,
  FCVAR_PRINTABLEONLY = 1 << 10,
  FCVAR_UNLOGGED = 1 << 11,
  FCVAR_NEVER_AS_STRING = 1 << 12,
  FCVAR_REPLICATED = 1 << 13,
  FCVAR_DEMO = 1 << 16,
  FCVAR_DONTRECORD = 1 << 17,
  FCVAR_NOT_CONNECTED = 1 << 22,
  FCVAR_ARCHIVE_XBOX = 1 << 24,
  FCVAR_SERVER_CAN_EXECUTE = 1 << 28,
  FCVAR_SERVER_CANNOT_QUERY = 1 << 29,
  FCVAR_CLIENTCMD_CAN_EXECUTE = 1 << 30
};

enum frame_stage {
  FRAME_UNDEFINED = -1,
  FRAME_START,
  FRAME_NET_UPDATE_START,
  FRAME_NET_UPDATE_POSTDATAUPDATE_START,
  FRAME_NET_UPDATE_POSTDATAUPDATE_END,
  FRAME_NET_UPDATE_END,
  FRAME_RENDER_START,
  FRAME_RENDER_END
};

enum player_flags {
  FL_ONGROUND = 1 << 0,
  FL_DUCKING = 1 << 1,
  FL_WATERJUMP = 1 << 2,
  FL_ONTRAIN = 1 << 3,
  FL_INRAIN = 1 << 4,
  FL_FROZEN = 1 << 5,
  FL_ATCONTROLS = 1 << 6,
  FL_CLIENT = 1 << 7,
  FL_FAKECLIENT = 1 << 8,
  FL_INWATER = 1 << 9,
  FL_FLY = 1 << 10,
  FL_SWIM = 1 << 11,
  FL_CONVEYOR = 1 << 12,
  FL_NPC = 1 << 13,
  FL_GODMODE = 1 << 14,
  FL_NOTARGET = 1 << 15,
  FL_AIMTARGET = 1 << 16,
  FL_PARTIALGROUND = 1 << 17,
  FL_STATICPROP = 1 << 18,
  FL_GRAPHED = 1 << 19,
  FL_GRENADE = 1 << 20,
  FL_STEPMOVEMENT = 1 << 21,
  FL_DONTTOUCH = 1 << 22,
  FL_BASEVELOCITY = 1 << 23,
  FL_WORLDBRUSH = 1 << 24,
  FL_OBJECT = 1 << 25,
  FL_KILLME = 1 << 26,
  FL_ONFIRE = 1 << 27,
  FL_DISSOLVING = 1 << 28,
  FL_TANSRAGDOLL = 1 << 29,
  FL_UNBLOCKABLE_BY_PLAYER = 1 << 30,
  IN_ATTACK = 1 << 0,
  IN_JUMP = 1 << 1,
  IN_DUCK = 1 << 2,
  IN_FORWARD = 1 << 3,
  IN_BACK = 1 << 4,
  IN_USE = 1 << 5,
  IN_CANCEL = 1 << 6,
  IN_LEFT = 1 << 7,
  IN_RIGHT = 1 << 8,
  IN_MOVELEFT = 1 << 9,
  IN_MOVERIGHT = 1 << 10,
  IN_ATTACK2 = 1 << 11,
  IN_RUN = 1 << 12,
  IN_RELOAD = 1 << 13,
  IN_ALT1 = 1 << 14,
  IN_ALT2 = 1 << 15,
  IN_SCORE = 1 << 16,
  IN_SPEED = 1 << 17,
  IN_WALK = 1 << 18,
  IN_ZOOM = 1 << 19,
  IN_WEAPON1 = 1 << 20,
  IN_WEAPON2 = 1 << 21,
  IN_BULLRUSH = 1 << 22,
  IN_GRENADE1 = 1 << 23,
  IN_GRENADE2 = 1 << 24,
  IN_ATTACK3  = 1 << 25
};

enum tf_cond{
  TF_COND_INVALID = -1,
  TF_COND_AIMING = 0,
  TF_COND_ZOOMED = 1,
  TF_COND_DISGUISING = 2,
  TF_COND_DISGUISED = 3,
  TF_COND_STEALTHED = 4,
  TF_COND_INVULNERABLE = 5,
  TF_COND_TELEPORTED = 6,
  TF_COND_TAUNTING = 7,
  TF_COND_INVULNERABLE_WEARINGOFF = 8,
  TF_COND_STEALTHED_BLINK = 9,
  TF_COND_SELECTED_TO_TELEPORT = 10,
  TF_COND_CRITBOOSTED = 11,
  TF_COND_TMPDAMAGEBONUS = 12,
  TF_COND_FEIGN_DEATH = 13,
  TF_COND_PHASE = 14,
  TF_COND_STUNNED = 15,
  TF_COND_OFFENSEBUFF = 16,
  TF_COND_SHIELD_CHARGE = 17,
  TF_COND_DEMO_BUFF = 18,
  TF_COND_ENERGY_BUFF = 19,
  TF_COND_RADIUSHEAL = 20,
  TF_COND_HEALTH_BUFF = 21,
  TF_COND_BURNING = 22,
  TF_COND_HEALTH_OVERHEALED = 23,
  TF_COND_URINE = 24,
  TF_COND_BLEEDING = 25,
  TF_COND_DEFENSEBUFF = 26,
  TF_COND_MAD_MILK = 27,
  TF_COND_MEGAHEAL = 28,
  TF_COND_REGENONDAMAGEBUFF = 29,
  TF_COND_MARKEDFORDEATH = 30,
  TF_COND_NOHEALINGDAMAGEBUFF = 31,
  TF_COND_SPEED_BOOST = 32,
  TF_COND_CRITBOOSTED_PUMPKIN = 33,
  TF_COND_CRITBOOSTED_USER_BUFF = 34,
  TF_COND_CRITBOOSTED_DEMO_CHARGE = 35,
  TF_COND_SODAPOPPER_HYPE = 36,
  TF_COND_CRITBOOSTED_FIRST_BLOOD = 37,
  TF_COND_CRITBOOSTED_BONUS_TIME = 38,
  TF_COND_CRITBOOSTED_CTF_CAPTURE = 39,
  TF_COND_CRITBOOSTED_ON_KILL = 40,
  TF_COND_CANNOT_SWITCH_FROM_MELEE = 41,
  TF_COND_DEFENSEBUFF_NO_CRIT_BLOCK = 42,
  TF_COND_REPROGRAMMED = 43,
  TF_COND_CRITBOOSTED_RAGE_BUFF = 44,
  TF_COND_DEFENSEBUFF_HIGH = 45,
  TF_COND_SNIPERCHARGE_RAGE_BUFF = 46,
  TF_COND_DISGUISE_WEARINGOFF = 47,
  TF_COND_MARKEDFORDEATH_SILENT = 48,
  TF_COND_DISGUISED_AS_DISPENSER = 49,
  TF_COND_SAPPED = 50,
  TF_COND_INVULNERABLE_HIDE_UNLESS_DAMAGED = 51,
  TF_COND_INVULNERABLE_USER_BUFF = 52,
  TF_COND_HALLOWEEN_BOMB_HEAD = 53,
  TF_COND_HALLOWEEN_THRILLER = 54,
  TF_COND_RADIUSHEAL_ON_DAMAGE = 55,
  TF_COND_CRITBOOSTED_CARD_EFFECT = 56,
  TF_COND_INVULNERABLE_CARD_EFFECT = 57,
  TF_COND_MEDIGUN_UBER_BULLET_RESIST = 58,
  TF_COND_MEDIGUN_UBER_BLAST_RESIST = 59,
  TF_COND_MEDIGUN_UBER_FIRE_RESIST = 60,
  TF_COND_MEDIGUN_SMALL_BULLET_RESIST = 61,
  TF_COND_MEDIGUN_SMALL_BLAST_RESIST = 62,
  TF_COND_MEDIGUN_SMALL_FIRE_RESIST = 63,
  TF_COND_STEALTHED_USER_BUFF = 64,
  TF_COND_MEDIGUN_DEBUFF = 65,
  TF_COND_STEALTHED_USER_BUFF_FADING = 66,
  TF_COND_BULLET_IMMUNE = 67,
  TF_COND_BLAST_IMMUNE = 68,
  TF_COND_FIRE_IMMUNE = 69,
  TF_COND_PREVENT_DEATH = 70,
  TF_COND_MVM_BOT_STUN_RADIOWAVE = 71,
  TF_COND_HALLOWEEN_SPEED_BOOST = 72,
  TF_COND_HALLOWEEN_QUICK_HEAL = 73,
  TF_COND_HALLOWEEN_GIANT = 74,
  TF_COND_HALLOWEEN_TINY = 75,
  TF_COND_HALLOWEEN_IN_HELL = 76,
  TF_COND_HALLOWEEN_GHOST_MODE = 77,
  TF_COND_MINICRITBOOSTED_ON_KILL = 78,
  TF_COND_OBSCURED_SMOKE = 79,
  TF_COND_PARACHUTE_ACTIVE = 80,
  TF_COND_BLASTJUMPING = 81,
  TF_COND_HALLOWEEN_KART = 82,
  TF_COND_HALLOWEEN_KART_DASH = 83,
  TF_COND_BALLOON_HEAD = 84,
  TF_COND_MELEE_ONLY = 85,
  TF_COND_SWIMMING_CURSE = 86,
  TF_COND_FREEZE_INPUT = 87,
  TF_COND_HALLOWEEN_KART_CAGE = 88,
  TF_COND_DONOTUSE_0 = 89,
  TF_COND_RUNE_STRENGTH = 90,
  TF_COND_RUNE_HASTE = 91,
  TF_COND_RUNE_REGEN = 92,
  TF_COND_RUNE_RESIST = 93,
  TF_COND_RUNE_VAMPIRE = 94,
  TF_COND_RUNE_REFLECT = 95,
  TF_COND_RUNE_PRECISION = 96,
  TF_COND_RUNE_AGILITY = 97,
  TF_COND_GRAPPLINGHOOK = 98,
  TF_COND_GRAPPLINGHOOK_SAFEFALL = 99,
  TF_COND_GRAPPLINGHOOK_LATCHED = 100,
  TF_COND_GRAPPLINGHOOK_BLEEDING = 101,
  TF_COND_AFTERBURN_IMMUNE = 102,
  TF_COND_RUNE_KNOCKOUT = 103,
  TF_COND_RUNE_IMBALANCE = 104,
  TF_COND_CRITBOOSTED_RUNE_TEMP = 105,
  TF_COND_PASSTIME_INTERCEPTION = 106,
  TF_COND_SWIMMING_NO_EFFECTS = 107,
  TF_COND_PURGATORY = 108,
  TF_COND_RUNE_KING = 109,
  TF_COND_RUNE_PLAGUE = 110,
  TF_COND_RUNE_SUPERNOVA = 111,
  TF_COND_PLAGUE = 112,
  TF_COND_KING_BUFFED = 113,
  TF_COND_TEAM_GLOWS = 114,
  TF_COND_KNOCKED_INTO_AIR = 115,
  TF_COND_COMPETITIVE_WINNER = 116,
  TF_COND_COMPETITIVE_LOSER = 117,
  TF_COND_HEALING_DEBUFF = 118,
  TF_COND_PASSTIME_PENALTY_DEBUFF = 119,
  TF_COND_GRAPPLED_TO_PLAYER = 120,
  TF_COND_GRAPPLED_BY_PLAYER = 121,
  TF_COND_PARACHUTE_DEPLOYED = 122,
  TF_COND_GAS = 123,
  TF_COND_BURNING_PYRO = 124,
  TF_COND_ROCKETPACK = 125,
  TF_COND_LOST_FOOTING = 126,
  TF_COND_AIR_CURRENT = 127,
  TF_COND_HALLOWEEN_HELL_HEAL = 128,
  TF_COND_POWERUPMODE_DOMINANT = 129,
  TF_COND_IMMUNE_TO_PUSHBACK = 130,
  TF_COND_COUNT = 160
};

enum tf_weapon_type
{
  TF_WEAPON_NONE = 0,
  TF_WEAPON_BAT,
  TF_WEAPON_BAT_WOOD,
  TF_WEAPON_BOTTLE,
  TF_WEAPON_FIREAXE,
  TF_WEAPON_CLUB,
  TF_WEAPON_CROWBAR,
  TF_WEAPON_KNIFE,
  TF_WEAPON_FISTS,
  TF_WEAPON_SHOVEL,
  TF_WEAPON_WRENCH,
  TF_WEAPON_BONESAW,
  TF_WEAPON_SHOTGUN_PRIMARY,
  TF_WEAPON_SHOTGUN_SOLDIER,
  TF_WEAPON_SHOTGUN_HWG,
  TF_WEAPON_SHOTGUN_PYRO,
  TF_WEAPON_SCATTERGUN,
  TF_WEAPON_SNIPERRIFLE,
  TF_WEAPON_MINIGUN,
  TF_WEAPON_SMG,
  TF_WEAPON_SYRINGEGUN_MEDIC,
  TF_WEAPON_TRANQ,
  TF_WEAPON_ROCKETLAUNCHER,
  TF_WEAPON_GRENADELAUNCHER,
  TF_WEAPON_PIPEBOMBLAUNCHER,
  TF_WEAPON_FLAMETHROWER,
  TF_WEAPON_GRENADE_NORMAL,
  TF_WEAPON_GRENADE_CONCUSSION,
  TF_WEAPON_GRENADE_NAIL,
  TF_WEAPON_GRENADE_MIRV,
  TF_WEAPON_GRENADE_MIRV_DEMOMAN,
  TF_WEAPON_GRENADE_NAPALM,
  TF_WEAPON_GRENADE_GAS,
  TF_WEAPON_GRENADE_EMP,
  TF_WEAPON_GRENADE_CALTROP,
  TF_WEAPON_GRENADE_PIPEBOMB,
  TF_WEAPON_GRENADE_SMOKE_BOMB,
  TF_WEAPON_GRENADE_HEAL,
  TF_WEAPON_GRENADE_STUNBALL,
  TF_WEAPON_GRENADE_JAR,
  TF_WEAPON_GRENADE_JAR_MILK,
  TF_WEAPON_PISTOL,
  TF_WEAPON_PISTOL_SCOUT,
  TF_WEAPON_REVOLVER,
  TF_WEAPON_NAILGUN,
  TF_WEAPON_PDA,
  TF_WEAPON_PDA_ENGINEER_BUILD,
  TF_WEAPON_PDA_ENGINEER_DESTROY,
  TF_WEAPON_PDA_SPY,
  TF_WEAPON_BUILDER,
  TF_WEAPON_MEDIGUN,
  TF_WEAPON_GRENADE_MIRVBOMB,
  TF_WEAPON_FLAMETHROWER_ROCKET,
  TF_WEAPON_GRENADE_DEMOMAN,
  TF_WEAPON_SENTRY_BULLET,
  TF_WEAPON_SENTRY_ROCKET,
  TF_WEAPON_DISPENSER,
  TF_WEAPON_INVIS,
  TF_WEAPON_FLAREGUN,
  TF_WEAPON_LUNCHBOX,
  TF_WEAPON_JAR,
  TF_WEAPON_COMPOUND_BOW,
  TF_WEAPON_BUFF_ITEM,
  TF_WEAPON_PUMPKIN_BOMB,
  TF_WEAPON_SWORD,
  TF_WEAPON_ROCKETLAUNCHER_DIRECTHIT,
  TF_WEAPON_LIFELINE,
  TF_WEAPON_LASER_POINTER,
  TF_WEAPON_DISPENSER_GUN,
  TF_WEAPON_SENTRY_REVENGE,
  TF_WEAPON_JAR_MILK,
  TF_WEAPON_HANDGUN_SCOUT_PRIMARY,
  TF_WEAPON_BAT_FISH,
  TF_WEAPON_CROSSBOW,
  TF_WEAPON_STICKBOMB,
  TF_WEAPON_HANDGUN_SCOUT_SECONDARY,
  TF_WEAPON_SODA_POPPER,
  TF_WEAPON_SNIPERRIFLE_DECAP,
  TF_WEAPON_RAYGUN,
  TF_WEAPON_PARTICLE_CANNON,
  TF_WEAPON_MECHANICAL_ARM,
  TF_WEAPON_DRG_POMSON,
  TF_WEAPON_BAT_GIFTWRAP,
  TF_WEAPON_GRENADE_ORNAMENT_BALL,
  TF_WEAPON_FLAREGUN_REVENGE,
  TF_WEAPON_PEP_BRAWLER_BLASTER,
  TF_WEAPON_CLEAVER,
  TF_WEAPON_GRENADE_CLEAVER,
  TF_WEAPON_STICKY_BALL_LAUNCHER,
  TF_WEAPON_GRENADE_STICKY_BALL,
  TF_WEAPON_SHOTGUN_BUILDING_RESCUE,
  TF_WEAPON_CANNON,
  TF_WEAPON_THROWABLE,
  TF_WEAPON_GRENADE_THROWABLE,
  TF_WEAPON_PDA_SPY_BUILD,
  TF_WEAPON_GRENADE_WATERBALLOON,
  TF_WEAPON_HARVESTER_SAW,
  TF_WEAPON_SPELLBOOK,
  TF_WEAPON_SPELLBOOK_PROJECTILE,
  TF_WEAPON_SNIPERRIFLE_CLASSIC,
  TF_WEAPON_PARACHUTE,
  TF_WEAPON_GRAPPLINGHOOK,
  TF_WEAPON_PASSTIME_GUN,
  TF_WEAPON_CHARGED_SMG,
  TF_WEAPON_COUNT
};

enum tf_dmg_custom
{
  TF_DMG_CUSTOM_NONE = 0,
  TF_DMG_CUSTOM_HEADSHOT,
  TF_DMG_CUSTOM_BACKSTAB,
  TF_DMG_CUSTOM_BURNING,
  TF_DMG_WRENCH_FIX,
  TF_DMG_CUSTOM_MINIGUN,
  TF_DMG_CUSTOM_SUICIDE,
  TF_DMG_CUSTOM_TAUNTATK_HADOUKEN,
  TF_DMG_CUSTOM_BURNING_FLARE,
  TF_DMG_CUSTOM_TAUNTATK_HIGH_NOON,
  TF_DMG_CUSTOM_TAUNTATK_GRAND_SLAM,
  TF_DMG_CUSTOM_PENETRATE_MY_TEAM,
  TF_DMG_CUSTOM_PENETRATE_ALL_PLAYERS,
  TF_DMG_CUSTOM_TAUNTATK_FENCING,
  TF_DMG_CUSTOM_PENETRATE_NONBURNING_TEAMMATE,
  TF_DMG_CUSTOM_TAUNTATK_ARROW_STAB,
  TF_DMG_CUSTOM_TELEFRAG,
  TF_DMG_CUSTOM_BURNING_ARROW,
  TF_DMG_CUSTOM_FLYINGBURN,
  TF_DMG_CUSTOM_PUMPKIN_BOMB,
  TF_DMG_CUSTOM_DECAPITATION,
  TF_DMG_CUSTOM_TAUNTATK_GRENADE,
  TF_DMG_CUSTOM_BASEBALL,
  TF_DMG_CUSTOM_CHARGE_IMPACT,
  TF_DMG_CUSTOM_TAUNTATK_BARBARIAN_SWING,
  TF_DMG_CUSTOM_AIR_STICKY_BURST,
  TF_DMG_CUSTOM_DEFENSIVE_STICKY,
  TF_DMG_CUSTOM_PICKAXE,
  TF_DMG_CUSTOM_ROCKET_DIRECTHIT,
  TF_DMG_CUSTOM_TAUNTATK_UBERSLICE,
  TF_DMG_CUSTOM_PLAYER_SENTRY,
  TF_DMG_CUSTOM_STANDARD_STICKY,
  TF_DMG_CUSTOM_SHOTGUN_REVENGE_CRIT,
  TF_DMG_CUSTOM_TAUNTATK_ENGINEER_GUITAR_SMASH,
  TF_DMG_CUSTOM_BLEEDING,
  TF_DMG_CUSTOM_GOLD_WRENCH,
  TF_DMG_CUSTOM_CARRIED_BUILDING,
  TF_DMG_CUSTOM_COMBO_PUNCH,
  TF_DMG_CUSTOM_TAUNTATK_ENGINEER_ARM_KILL,
  TF_DMG_CUSTOM_FISH_KILL,
  TF_DMG_CUSTOM_TRIGGER_HURT,
  TF_DMG_CUSTOM_DECAPITATION_BOSS,
  TF_DMG_CUSTOM_STICKBOMB_EXPLOSION,
  TF_DMG_CUSTOM_AEGIS_ROUND,
  TF_DMG_CUSTOM_FLARE_EXPLOSION,
  TF_DMG_CUSTOM_BOOTS_STOMP,
  TF_DMG_CUSTOM_PLASMA,
  TF_DMG_CUSTOM_PLASMA_CHARGED,
  TF_DMG_CUSTOM_PLASMA_GIB,
  TF_DMG_CUSTOM_PRACTICE_STICKY,
  TF_DMG_CUSTOM_EYEBALL_ROCKET,
  TF_DMG_CUSTOM_HEADSHOT_DECAPITATION,
  TF_DMG_CUSTOM_TAUNTATK_ARMAGEDDON,
  TF_DMG_CUSTOM_FLARE_PELLET,
  TF_DMG_CUSTOM_CLEAVER,
  TF_DMG_CUSTOM_CLEAVER_CRIT,
  TF_DMG_CUSTOM_SAPPER_RECORDER_DEATH,
  TF_DMG_CUSTOM_MERASMUS_PLAYER_BOMB,
  TF_DMG_CUSTOM_MERASMUS_GRENADE,
  TF_DMG_CUSTOM_MERASMUS_ZAP,
  TF_DMG_CUSTOM_MERASMUS_DECAPITATION,
  TF_DMG_CUSTOM_CANNONBALL_PUSH,
  TF_DMG_CUSTOM_TAUNTATK_ALLCLASS_GUITAR_RIFF,
  TF_DMG_CUSTOM_THROWABLE,
  TF_DMG_CUSTOM_THROWABLE_KILL,
  TF_DMG_CUSTOM_SPELL_TELEPORT,
  TF_DMG_CUSTOM_SPELL_SKELETON,
  TF_DMG_CUSTOM_SPELL_MIRV,
  TF_DMG_CUSTOM_SPELL_METEOR,
  TF_DMG_CUSTOM_SPELL_LIGHTNING,
  TF_DMG_CUSTOM_SPELL_FIREBALL,
  TF_DMG_CUSTOM_SPELL_MONOCULUS,
  TF_DMG_CUSTOM_SPELL_BLASTJUMP,
  TF_DMG_CUSTOM_SPELL_BATS,
  TF_DMG_CUSTOM_SPELL_TINY,
  TF_DMG_CUSTOM_KART,
  TF_DMG_CUSTOM_GIANT_HAMMER,
  TF_DMG_CUSTOM_RUNE_REFLECT,

  TF_DMG_CUSTOM_END // END
};

enum player_class{
  TF_CLASS_SCOUT = 1,
  TF_CLASS_SNIPER = 2,
  TF_CLASS_SOLDIER = 3,
  TF_CLASS_DEMOMAN = 4,
  TF_CLASS_MEDIC = 5,
  TF_CLASS_HEAVY = 6,
  TF_CLASS_PYRO = 7,
  TF_CLASS_SPY = 8,
  TF_CLASS_ENGINEER = 9,
  TF_CLASS_MAX = 9,
};

enum player_team {
  TEAM_NONE = 0,
  TEAM_RED = 2,
  TEAM_BLU = 3
};

enum view_clear_flags
{
  VIEW_CLEAR_COLOR = 0x1,
  VIEW_CLEAR_DEPTH = 0x2,
  VIEW_CLEAR_FULL_TARGET = 0x4,
  VIEW_NO_DRAW = 0x8,
  VIEW_CLEAR_OBEY_STENCIL = 0x10,
  VIEW_CLEAR_STENCIL = 0x20,
};

enum player_movetype {
  MOVETYPE_NONE = 0,
  MOVETYPE_ISOMETRIC,
  MOVETYPE_WALK,
  MOVETYPE_STEP,
  MOVETYPE_FLY,
  MOVETYPE_FLYGRAVITY,
  MOVETYPE_VPHYSICS,
  MOVETYPE_PUSH,
  MOVETYPE_NOCLIP,
  MOVETYPE_LADDER,
  MOVETYPE_OBSERVER,
  MOVETYPE_CUSTOM,
  MOVETYPE_LAST = MOVETYPE_CUSTOM,
  MOVETYPE_MAX_BITS = 4
};

enum vaccinator_resist_types{
  RESIST_TYPE_INVALID = -1,
  RESIST_TYPE_BULLET,
  RESIST_TYPE_BLAST,
  RESIST_TYPE_FIRE,
};

enum trace_type {
  TRACE_EVERYTHING = 0,
  TRACE_WORLD_ONLY,
  TRACE_ENTITIES_ONLY,
  TRACE_EVERYTHING_FILTER_PROPS,
};

enum hit_groups{
  hitgroup_generic = 0,
  hitgroup_head = 1,
  hitgroup_chest = 2,
  hitgroup_stomach = 3,
  hitgroup_leftarm = 4,
  hitgroup_rightarm = 5,
  hitgroup_leftleg = 6,
  hitgroup_rightleg = 7,
  hitgroup_gear = 10,
};

enum trace_mask {
  mask_all                    = 0xFFFFFFFF,
  mask_solid                  = 0x200400B,
  mask_playersolid            = 0x201400B,
  mask_npcsolid               = 0x202400B,
  mask_npcfluid               = 0x2024003,
  mask_water                  = 0x4030,
  mask_opaque                 = 0x40A0,
  mask_opaque_npc             = 0x20040A0,
  mask_blocklos               = 0x4011,
  mask_blocklos_npc           = 0x2004011,
  mask_visible                = 0x60A0,
  mask_visible_npc            = 0x20060A0,
  mask_shot                   = 0x46004003,
  mask_shot_brushonly         = 0x4004003,
  mask_shot_hull              = 0x600400B,
  mask_shot_portal            = 0x2004003,
  mask_solid_brushonly        = 0x400B,
  mask_playersolid_brushonly  = 0x1400B,
  mask_npcsolid_brushonly     = 0x2400B,
  mask_npcworldstatic         = 0x2000B,
  mask_npcworldstatic_fluid   = 0x20003,
  mask_splitareaportal        = 0x30,
  mask_current                = 0xFC0000,
  mask_deadsolid              = 0x1000B,
  mask_shot_hitbox            = 0x4600400B,

  // ray trace bullet mask
  mask_bullet                 = 0x4200400B,
  mask_explosion              = 0x6004003,

  contents_water              = 32,
};

enum render_view_info {
  RENDERVIEW_UNSPECIFIED   = 0,
  RENDERVIEW_DRAWVIEWMODEL = (1<<0),
  RENDERVIEW_DRAWHUD      = (1<<1),
  RENDERVIEW_SUPPRESSMONITORRENDERING = (1<<2),
};

enum query_cvar_status{
  query_cvar_value_intact = 0,
  query_cvar_value_not_found = 1,
  query_cvar_value_not_a_cvar = 2,
  query_cvar_value_protected = 3,
};

enum material_flags {
  MATERIAL_VAR_DEBUG = ( 1 << 0 ),
  MATERIAL_VAR_NO_DEBUG_OVERRIDE = ( 1 << 1 ),
  MATERIAL_VAR_NO_DRAW = ( 1 << 2 ),
  MATERIAL_VAR_USE_IN_FILLRATE_MODE = ( 1 << 3 ),

  MATERIAL_VAR_VERTEXCOLOR = ( 1 << 4 ),
  MATERIAL_VAR_VERTEXALPHA = ( 1 << 5 ),
  MATERIAL_VAR_SELFILLUM = ( 1 << 6 ),
  MATERIAL_VAR_ADDITIVE = ( 1 << 7 ),
  MATERIAL_VAR_ALPHATEST = ( 1 << 8 ),
  MATERIAL_VAR_MULTIPASS = ( 1 << 9 ),
  MATERIAL_VAR_ZNEARER = ( 1 << 10 ),
  MATERIAL_VAR_MODEL = ( 1 << 11 ),
  MATERIAL_VAR_FLAT = ( 1 << 12 ),
  MATERIAL_VAR_NOCULL = ( 1 << 13 ),
  MATERIAL_VAR_NOFOG = ( 1 << 14 ),
  MATERIAL_VAR_IGNOREZ = ( 1 << 15 ),
  MATERIAL_VAR_DECAL = ( 1 << 16 ),
  MATERIAL_VAR_ENVMAPSPHERE = ( 1 << 17 ),
  MATERIAL_VAR_NOALPHAMOD = ( 1 << 18 ),
  MATERIAL_VAR_ENVMAPCAMERASPACE = ( 1 << 19 ),
  MATERIAL_VAR_BASEALPHAENVMAPMASK = ( 1 << 20 ),
  MATERIAL_VAR_TRANSLUCENT = ( 1 << 21 ),
  MATERIAL_VAR_NORMALMAPALPHAENVMAPMASK = ( 1 << 22 ),
  MATERIAL_VAR_NEEDS_SOFTWARE_SKINNING = ( 1 << 23 ),
  MATERIAL_VAR_OPAQUETEXTURE = ( 1 << 24 ),
  MATERIAL_VAR_ENVMAPMODE = ( 1 << 25 ),
  MATERIAL_VAR_SUPPRESS_DECALS = ( 1 << 26 ),
  MATERIAL_VAR_HALFLAMBERT = ( 1 << 27 ),
  MATERIAL_VAR_WIREFRAME = ( 1 << 28 ),
  MATERIAL_VAR_ALLOWALPHATOCOVERAGE = ( 1 << 29 ),
  MATERIAL_VAR_IGNORE_ALPHA_MODULATION = ( 1 << 30 ),
};

enum render_group_config{
  RENDER_GROUP_CFG_NUM_OPAQUE_ENT_BUCKETS = 4,
};

enum render_group{
  RENDER_GROUP_OPAQUE_STATIC_HUGE     = 0,    // Huge static prop
  RENDER_GROUP_OPAQUE_ENTITY_HUGE     = 1,    // Huge opaque entity
  RENDER_GROUP_OPAQUE_STATIC = RENDER_GROUP_OPAQUE_STATIC_HUGE + ( RENDER_GROUP_CFG_NUM_OPAQUE_ENT_BUCKETS - 1 ) * 2,
  RENDER_GROUP_OPAQUE_ENTITY,         // Opaque entity (smallest size, or default)

  RENDER_GROUP_TRANSLUCENT_ENTITY,
  RENDER_GROUP_TWOPASS,           // Implied opaque and translucent in two passes
  RENDER_GROUP_VIEW_MODEL_OPAQUE,       // Solid weapon view models
  RENDER_GROUP_VIEW_MODEL_TRANSLUCENT,    // Transparent overlays etc

  RENDER_GROUP_OPAQUE_BRUSH,          // Brushes

  RENDER_GROUP_OTHER,             // Unclassfied. Won't get drawn.

  // This one's always gotta be last
  RENDER_GROUP_COUNT
};

enum shader_stencil_op{
  STENCILOPERATION_KEEP = 1,
  STENCILOPERATION_ZERO = 2,
  STENCILOPERATION_REPLACE = 3,
  STENCILOPERATION_INCRSAT = 4,
  STENCILOPERATION_DECRSAT = 5,
  STENCILOPERATION_INVERT = 6,
  STENCILOPERATION_INCR = 7,
  STENCILOPERATION_DECR = 8,
};

enum stencil_comparison_function{
  STENCILCOMPARISONFUNCTION_NEVER = 1,
  STENCILCOMPARISONFUNCTION_LESS = 2,
  STENCILCOMPARISONFUNCTION_EQUAL = 3,
  STENCILCOMPARISONFUNCTION_LESSEQUAL = 4,
  STENCILCOMPARISONFUNCTION_GREATER = 5,
  STENCILCOMPARISONFUNCTION_NOTEQUAL = 6,
  STENCILCOMPARISONFUNCTION_GREATEREQUAL = 7,
  STENCILCOMPARISONFUNCTION_ALWAYS = 8,
  STENCILCOMPARISONFUNCTION_FORCE_DWORD = 0x7FFFFFFF
};

enum compiled_vtf_flags
{
  // flags from the *.txt config file
  TEXTUREFLAGS_POINTSAMPLE = 0x00000001,
  TEXTUREFLAGS_TRILINEAR = 0x00000002,
  TEXTUREFLAGS_CLAMPS = 0x00000004,
  TEXTUREFLAGS_CLAMPT = 0x00000008,
  TEXTUREFLAGS_ANISOTROPIC = 0x00000010,
  TEXTUREFLAGS_HINT_DXT5 = 0x00000020,
  TEXTUREFLAGS_SRGB = 0x00000040,
  TEXTUREFLAGS_NORMAL = 0x00000080,
  TEXTUREFLAGS_NOMIP = 0x00000100,
  TEXTUREFLAGS_NOLOD = 0x00000200,
  TEXTUREFLAGS_ALL_MIPS = 0x00000400,
  TEXTUREFLAGS_PROCEDURAL = 0x00000800,

  // These are automatically generated by vtex from the texture data.
  TEXTUREFLAGS_ONEBITALPHA = 0x00001000,
  TEXTUREFLAGS_EIGHTBITALPHA = 0x00002000,

  // newer flags from the *.txt config file
  TEXTUREFLAGS_ENVMAP = 0x00004000,
  TEXTUREFLAGS_RENDERTARGET = 0x00008000,
  TEXTUREFLAGS_DEPTHRENDERTARGET = 0x00010000,
  TEXTUREFLAGS_NODEBUGOVERRIDE = 0x00020000,
  TEXTUREFLAGS_SINGLECOPY = 0x00040000,

  TEXTUREFLAGS_STAGING_MEMORY = 0x00080000,
  TEXTUREFLAGS_IMMEDIATE_CLEANUP = 0x00100000,
  TEXTUREFLAGS_IGNORE_PICMIP = 0x00200000,

  TEXTUREFLAGS_UNUSED_00400000 = 0x00400000,

  TEXTUREFLAGS_NODEPTHBUFFER = 0x00800000,

  TEXTUREFLAGS_UNUSED_01000000 = 0x01000000,

  TEXTUREFLAGS_CLAMPU = 0x02000000,

  TEXTUREFLAGS_VERTEXTEXTURE = 0x04000000,          // Useable as a vertex texture

  TEXTUREFLAGS_SSBUMP = 0x08000000,

  TEXTUREFLAGS_UNUSED_10000000 = 0x10000000,

  // Clamp to border color on all texture coordinates
  TEXTUREFLAGS_BORDER = 0x20000000,

  TEXTUREFLAGS_STREAMABLE_COARSE = 0x40000000,
  TEXTUREFLAGS_STREAMABLE_FINE = 0x80000000,
  TEXTUREFLAGS_STREAMABLE = (TEXTUREFLAGS_STREAMABLE_COARSE | TEXTUREFLAGS_STREAMABLE_FINE)
};

enum render_target_size_mode
{
  RT_SIZE_NO_CHANGE = 0,      // Only allowed for render targets that don't want a depth buffer
  // (because if they have a depth buffer, the render target must be less than or equal to the size of the framebuffer).
  RT_SIZE_DEFAULT = 1,        // Don't play with the specified width and height other than making sure it fits in the framebuffer.
  RT_SIZE_PICMIP = 2,       // Apply picmip to the render target's width and height.
  RT_SIZE_HDR = 3,          // frame_buffer_width / 4
  RT_SIZE_FULL_FRAME_BUFFER = 4,  // Same size as frame buffer, or next lower power of 2 if we can't do that.
  RT_SIZE_OFFSCREEN = 5,      // Target of specified size, don't mess with dimensions
  RT_SIZE_FULL_FRAME_BUFFER_ROUNDED_UP = 6, // Same size as the frame buffer, rounded up if necessary for systems that can't do non-power of two textures.
  RT_SIZE_REPLAY_SCREENSHOT = 7,  // Rounded down to power of 2, essentially...
  RT_SIZE_LITERAL = 8,      // Use the size passed in. Don't clamp it to the frame buffer size. Really.
  RT_SIZE_LITERAL_PICMIP = 9    // Use the size passed in, don't clamp to the frame buffer size, but do apply picmip restrictions.
};

enum material_render_target_depth
{
  MATERIAL_RT_DEPTH_SHARED = 0x0,
  MATERIAL_RT_DEPTH_SEPARATE = 0x1,
  MATERIAL_RT_DEPTH_NONE = 0x2,
  MATERIAL_RT_DEPTH_ONLY = 0x3,
};

enum image_format
{
  IMAGE_FORMAT_UNKNOWN = -1,
  IMAGE_FORMAT_RGBA8888 = 0,
  IMAGE_FORMAT_ABGR8888,
  IMAGE_FORMAT_RGB888,
  IMAGE_FORMAT_BGR888,
  IMAGE_FORMAT_RGB565,
  IMAGE_FORMAT_I8,
  IMAGE_FORMAT_IA88,
  IMAGE_FORMAT_P8,
  IMAGE_FORMAT_A8,
  IMAGE_FORMAT_RGB888_BLUESCREEN,
  IMAGE_FORMAT_BGR888_BLUESCREEN,
  IMAGE_FORMAT_ARGB8888,
  IMAGE_FORMAT_BGRA8888,
  IMAGE_FORMAT_DXT1,
  IMAGE_FORMAT_DXT3,
  IMAGE_FORMAT_DXT5,
  IMAGE_FORMAT_BGRX8888,
  IMAGE_FORMAT_BGR565,
  IMAGE_FORMAT_BGRX5551,
  IMAGE_FORMAT_BGRA4444,
  IMAGE_FORMAT_DXT1_ONEBITALPHA,
  IMAGE_FORMAT_BGRA5551,
  IMAGE_FORMAT_UV88,
  IMAGE_FORMAT_UVWQ8888,
  IMAGE_FORMAT_RGBA16161616F,
  IMAGE_FORMAT_RGBA16161616,
  IMAGE_FORMAT_UVLX8888,
  IMAGE_FORMAT_R32F,      // Single-channel 32-bit floating point
  IMAGE_FORMAT_RGB323232F,
  IMAGE_FORMAT_RGBA32323232F,

  // Depth-stencil texture formats for shadow depth mapping
  IMAGE_FORMAT_NV_DST16,    //
  IMAGE_FORMAT_NV_DST24,    //
  IMAGE_FORMAT_NV_INTZ,   // Vendor-specific depth-stencil texture
  IMAGE_FORMAT_NV_RAWZ,   // formats for shadow depth mapping
  IMAGE_FORMAT_ATI_DST16,   //
  IMAGE_FORMAT_ATI_DST24,   //
  IMAGE_FORMAT_NV_NULL,   // Dummy format which takes no video memory

  // Compressed normal map formats
  IMAGE_FORMAT_ATI2N,     // One-surface ATI2N / DXN format
  IMAGE_FORMAT_ATI1N,     // Two-surface ATI1N format

  IMAGE_FORMAT_DXT1_RUNTIME,
  IMAGE_FORMAT_DXT5_RUNTIME,

  NUM_IMAGE_FORMATS
};

enum explosion_type{
  EXPLOSION_ROCKET = 1,
  EXPLOSION_DEMO = 2,
  EXPLOSION_THROWABLE = 3,
  EXPLOSION_PYRO = 4,
};

// rijin enums
#define MAX_PLAYERS_POSSIBLE 129