#include "link.h"

#if !defined(DISABLE_NETWORKING)
  volatile u32 NET_FRAGMENT_SECURITY_FLAG = (NET_FRAGMENT_SECURITY_FLAG_CT | NET_FRAGMENT_SECURITY_FLAG_GEN);
  volatile u32 NET_FRAGMENT_EXTRA_FLAG    = 0;
#endif